version: "3.0"

services:
  elastic:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node


  sw-app:
    image: cimbonda/sw-app:v3
    ports:
    - 8988:8989
    environment:
      - ELASTICSEARCH_HOST=elastic